var img= document.getElementById("img1");
var text1= document.getElementById("t1");
var text2=document.getElementById("t2");
var text3=document.getElementById("t3");
var d=document.getElementById("t4")
var button1=document.getElementById("btn1");
var button2=document.getElementById("btn2");
var about=document.getElementById("abt");
var text4=document.getElementById("pax");
var text5=document.getElementById("hel");
var text6=document.getElementById("paxx");
var img1=document.getElementById("imgp");
var d2=document.getElementById("prog");
var c1=document.getElementById("card-1");
var c2=document.getElementById("card-2");
var c3=document.getElementById("card-3");
var d3=document.getElementById("d3");
var d4=document.getElementById("d4");
var d5=document.getElementById("row5");
var d6=document.getElementById("row6");
var d7=document.getElementById("row7");
var d8=document.getElementById("form");
var d9=document.getElementById("loc");
button1.addEventListener("mouseenter", function(){
button1.classList.add("bh");
});
button1.addEventListener("mouseleave" ,function(){
button1.classList.remove("bh");
});
button2.addEventListener("mouseenter", function(){
    button2.classList.add("bh");
    });
    button2.addEventListener("mouseleave" ,function(){
    button2.classList.remove("bh");
    });
window.addEventListener("DOMContentLoaded" ,function(){

    img.classList.remove("right");
    void img.offsetWidth;
    img.classList.add("right");
    text1.classList.remove("left");
    void text1.offsetWidth;
    text1.classList.add("left");
    text2.classList.remove("right");
    void text2.offsetWidth;
    text2.classList.add("right");
    text3.classList.remove("left");
    void text3.offsetWidth;
    text3.classList.add("left");
    d.classList.remove("left");
    void d.offsetWidth;
    d.classList.add("left");
    button1.classList.remove("left");
    void button1.offsetWidth;
    button1.classList.add("left");
    button2.classList.remove("right");
    void button2.offsetWidth;
    button2.classList.add("right");
});
window.addEventListener("DOMContentLoaded" ,function(){
    about.classList.remove("right");
    void about.offsetWidth;
    about.classList.add("right");
    text4.classList.remove("left");
    void text4.offsetWidth;
    text4.classList.add("left");
    img1.classList.remove("left");
    void img1.offsetWidth;
    img1.classList.add("left");
    text5.classList.remove("right");
    void text5.offsetWidth;
    text5.classList.add("right");
    text6.classList.remove("up");
    void text6.offsetWidth;
    text6.classList.add("up");
    d2.classList.remove("right");
    void d2.offsetWidth;
    d2.classList.add("right");
    d3.classList.remove("up");
    void d3.offsetWidth;
    d3.classList.add("up");
    c1.classList.remove("left");
    void c1.offsetWidth;
    c1.classList.add("left");
    c2.classList.remove("up");
    void c2.offsetWidth;
    c2.classList.add("up");
    c3.classList.remove("right");
    void c3.offsetWidth;
    c3.classList.add("right");
    d4.classList.remove("left");
    void d4.offsetWidth;
    d4.classList.add("left");
    d5.classList.remove("left");
    void d5.offsetWidth;
    d5.classList.add("left");
    d6.classList.remove("right");
    void d6.offsetWidth;
    d6.classList.add("right");
    d7.classList.remove("left");
    void d7.offsetWidth;
    d7.classList.add("left");
    d8.classList.remove("left");
    void d8.offsetWidth;
    d8.classList.add("left");
    d9.classList.remove("right");
    void d9.offsetWidth;
    d9.classList.add("right");
});